apiVersion: v1
kind: Service
metadata:
  name: application
  namespace: sqldb
  labels:
    app: employees
spec:
  type: NodePort
  selector:
    app: employees
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001