apiVersion: v1
kind: Pod
metadata:
  name: application
  namespace: webapp
  labels:
    app: employees
    component: frontend
spec:
  containers:
    - name: application-container
      image: 092659312972.dkr.ecr.us-east-1.amazonaws.com/soham-assignment2:app1.0
      env:
        - name: DBPWD
          value: pass
        - name: DBUSER
          value: root
        - name: DBHOST
          value: mysql.database.svc.cluster.local
        - name: DBPORT
          value: "3306"
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: ecr-secret